#!/usr/bin/env python
# -*- coding: utf-8 -*-

# mainfile (path relativo)
# iconfile (path relativo)
# GnomeCat (GTK;GNOME;Juegos;)
# GnomeMimeTypes

import os
import commands

self_path = os.path.abspath(os.path.dirname(__file__))

NAME = self_path.split("/")[-1]

final_path = os.path.join(os.environ["HOME"], NAME)
print "final_path =", final_path

### borrar anterior.
if os.path.exists(final_path):
    print "Eliminando Version Anterior."
    commands.getoutput('rm -r %s' % (final_path))

### Copiar proyecto a destino final.
commands.getoutput('cp -r %s %s' % (self_path, os.environ["HOME"]))
commands.getoutput('chmod 755 -R %s' % final_path)
print "Copiando:", self_path, "En:", os.environ["HOME"]

main_path = os.path.join(final_path, "mainfile")
icon_path = final_path + "iconfile"

desktoptext = """[Desktop Entry]
Encoding=UTF-8
Name=%s
GenericName=%s
Exec=%s
Terminal=false
Type=Application
Icon=%s
Categories=%s
MimeType=%s
StartupNotify=true""" % (NAME, NAME, main_path,
    icon_path, "GnomeCat", "GnomeMimeTypes")

print "\t Generando Archivo Desktop:"
print desktoptext

if not os.path.exists(os.path.join(os.environ["HOME"],
    '.local')):
    os.mkdir(os.path.join(os.environ["HOME"], '.local'))
    
if not os.path.exists(os.path.join(os.environ["HOME"],
    '.local/bin')):
    os.mkdir(os.path.join(os.environ["HOME"], '.local/bin'))
    
if not os.path.exists(os.path.join(os.environ["HOME"],
    '.local/share')):
    os.mkdir(os.path.join(os.environ["HOME"], '.local/share'))
    
if not os.path.exists(os.path.join(os.environ["HOME"],
    '.local/share/applications')):
    os.mkdir(os.path.join(os.environ["HOME"], '.local/share/applications'))
    
desktop = open(os.path.join(os.environ["HOME"],
    ".local/share/applications/%s.desktop" % NAME), "w")
desktop.write(desktoptext)
desktop.close()

commands.getoutput('chmod 755 %s' % os.path.join(os.environ["HOME"],
    ".local/share/applications/%s.desktop" % NAME))
commands.getoutput("update-desktop-database %s" % os.path.join(
    os.environ["HOME"], ".local/share/applications/"))
print "Instalacion Finalizada."
